services:
  - type: web
    name: abs-tracker
    runtime: python
    buildCommand: pip install poetry && poetry install --only main
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.14"
